// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.EF.Models;

public partial class LikeList
{
    /// <summary>
    /// 喜好清單流水號
    /// </summary>
    public int LikeListNo { get; set; }

    /// <summary>
    /// 產品流水號
    /// </summary>
    public int ProductNo { get; set; }

    /// <summary>
    /// 產品名稱
    /// </summary>
    public string ProductName { get; set; }

    /// <summary>
    /// 產品數量
    /// </summary>
    public int ProductCount { get; set; }

    /// <summary>
    /// 使用者ID
    /// </summary>
    public int UserID { get; set; }

    /// <summary>
    /// 扣款帳號
    /// </summary>
    public string Account { get; set; }

    /// <summary>
    /// Email
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// 產品價格
    /// </summary>
    public decimal Price { get; set; }

    /// <summary>
    /// 手續費率
    /// </summary>
    public decimal FeeRate { get; set; }

    /// <summary>
    /// 總產品價錢
    /// </summary>
    public decimal TotalPrice { get; set; }

    /// <summary>
    /// 總手續費用(台幣計價)
    /// </summary>
    public decimal TotalFee { get; set; }

    /// <summary>
    /// 預計扣款總金額
    /// </summary>
    public decimal TotalAmount { get; set; }

    /// <summary>
    /// 建立者ID
    /// </summary>
    public int CreateId { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime CreateTime { get; set; }

    /// <summary>
    /// 更新者ID
    /// </summary>
    public int? UpdateId { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    public DateTime? UpdateTime { get; set; }
}